[2024-12-27T12:06:19.568-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T12:06:19.596-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T12:01:17.120650-03:00 [queued]>
[2024-12-27T12:06:19.609-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T12:01:17.120650-03:00 [queued]>
[2024-12-27T12:06:19.609-0300] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-27T12:06:19.627-0300] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-27 12:01:17.120650-03:00
[2024-12-27T12:06:19.645-0300] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1402) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-27T12:06:19.646-0300] {standard_task_runner.py:72} INFO - Started process 1403 to run task
[2024-12-27T12:06:19.645-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-27T12:01:17.120650-03:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmpfeg16iv6']
[2024-12-27T12:06:19.649-0300] {standard_task_runner.py:105} INFO - Job 337: Subtask run_my_python_app
[2024-12-27T12:06:19.744-0300] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T12:01:17.120650-03:00 [running]> on host f657cc3f60f7
[2024-12-27T12:06:19.914-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T12:01:17.120650-03:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T12:01:17.120650-03:00'
[2024-12-27T12:06:19.915-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T12:06:19.974-0300] {docker.py:379} INFO - Starting docker container from image hello-world:latest
[2024-12-27T12:06:20.314-0300] {docker.py:73} INFO - 
[2024-12-27T12:06:20.314-0300] {docker.py:73} INFO - Hello from Docker!
[2024-12-27T12:06:20.315-0300] {docker.py:73} INFO - This message shows that your installation appears to be working correctly.
[2024-12-27T12:06:20.315-0300] {docker.py:73} INFO - 
[2024-12-27T12:06:20.316-0300] {docker.py:73} INFO - To generate this message, Docker took the following steps:
[2024-12-27T12:06:20.316-0300] {docker.py:73} INFO -  1. The Docker client contacted the Docker daemon.
[2024-12-27T12:06:20.317-0300] {docker.py:73} INFO -  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
[2024-12-27T12:06:20.317-0300] {docker.py:73} INFO -     (amd64)
[2024-12-27T12:06:20.318-0300] {docker.py:73} INFO -  3. The Docker daemon created a new container from that image which runs the
[2024-12-27T12:06:20.318-0300] {docker.py:73} INFO -     executable that produces the output you are currently reading.
[2024-12-27T12:06:20.318-0300] {docker.py:73} INFO -  4. The Docker daemon streamed that output to the Docker client, which sent it
[2024-12-27T12:06:20.319-0300] {docker.py:73} INFO -     to your terminal.
[2024-12-27T12:06:20.319-0300] {docker.py:73} INFO - 
[2024-12-27T12:06:20.319-0300] {docker.py:73} INFO - To try something more ambitious, you can run an Ubuntu container with:
[2024-12-27T12:06:20.320-0300] {docker.py:73} INFO -  $ docker run -it ubuntu bash
[2024-12-27T12:06:20.320-0300] {docker.py:73} INFO - 
[2024-12-27T12:06:20.320-0300] {docker.py:73} INFO - Share images, automate workflows, and more with a free Docker ID:
[2024-12-27T12:06:20.321-0300] {docker.py:73} INFO -  https://hub.docker.com/
[2024-12-27T12:06:20.321-0300] {docker.py:73} INFO - 
[2024-12-27T12:06:20.321-0300] {docker.py:73} INFO - For more examples and ideas, visit:
[2024-12-27T12:06:20.322-0300] {docker.py:73} INFO -  https://docs.docker.com/get-started/
[2024-12-27T12:06:20.627-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T12:06:20.628-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-27T12:01:17.120650-03:00, execution_date=20241227T120117, start_date=20241227T120619, end_date=20241227T120620
[2024-12-27T12:06:20.664-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-27T12:06:20.702-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T12:06:20.705-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
